version: "3"

networks:
  docker-tempo:

services:
  loki:
    image: grafana/loki:2.2.0
    container_name: loki
    volumes:
      - ./etc/loki.yaml:/etc/loki.yaml
      # loki log path
      - ./etc/data/loki-data:/tmp/loki
    ports:
      - "3200:3200"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    command: -config.file=/etc/loki.yaml
    networks:
      - docker-tempo
    depends_on:
      - tempo

  promtail:
    image: grafana/promtail:2.2.0
    container_name: promtail
    volumes:
      #  *.log path
      - ./etc/data/app_log/:/var/log/
      - ./etc/promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - docker-tempo
    depends_on:
      - loki

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - docker-tempo

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./etc/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - docker-tempo

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo.yaml
    restart: unless-stopped
    ports:
      - "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
      - "55680:55680"  # OpenTelemetry
      - "3100:3100"   # tempo
      - "6831:6831"
      - "9411:9411"
    networks:
      - docker-tempo

  tempo-query:
    image: grafana/tempo-query:latest
    container_name: tempo-query
    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml" ]
    volumes:
      - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    depends_on:
      - tempo
    networks:
      - docker-tempo
