version: "3"

networks:
  docker-tempo:

services:
  loki:
    image: grafana/loki:2.2.0
    container_name: loki
    volumes:
      #    将loki的配置文件挂载到本地 c:/docker/loki 目录
      - /Users/zhumingyuan/java_workspace/boot-opentelemetry-tempo-simply/etc/loki.yaml:/etc/loki.yaml
    ports:
      - "3200:3200"
    command: -config.file=/etc/loki.yaml
    networks:
      - docker-tempo

  promtail:
    image: grafana/promtail:2.2.0
    container_name: promtail
    volumes:
      #  为了读取本地的日志目录，这个是个默认配置目的就是为跑起来，生产肯定不是这样的。
      - /Users/zhumingyuan/java_workspace/boot-opentelemetry-tempo-simply/etc/data/app_log/:/var/log/
      #  promtail  的配置文件也挂载到本地 c:/docker/promtail目录
      - /Users/zhumingyuan/java_workspace/boot-opentelemetry-tempo-simply/etc/promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - docker-tempo
    depends_on:
      - loki

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    volumes:
      - /Users/zhumingyuan/java_workspace/boot-opentelemetry-tempo-simply/etc/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - docker-tempo

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - docker-tempo

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo-local.yaml" ]
    volumes:
      - /Users/zhumingyuan/java_workspace/boot-opentelemetry-tempo-simply/etc/tempo-local.yaml:/etc/tempo-local.yaml
    restart: unless-stopped
    ports:
      - "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
      - "55680:55680"  # OpenTelemetry
      - "3100:3100"   # tempo
      - "6831:6831"
      - "9411:9411"
    networks:
      - docker-tempo

  tempo-query:
    image: grafana/tempo-query:latest
    container_name: tempo-query
    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml" ]
    volumes:
      - /Users/zhumingyuan/java_workspace/boot-opentelemetry-tempo-simply/etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    depends_on:
      - tempo
    networks:
      - docker-tempo
